export const Main = () => {
    return (<>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
        <div>siema</div>
      </>
    );
};
